language: java
jdk:
  - openjdk8

install:
  - wget https://github.com/laurentC35/Lunatic-Model/releases/download/1.0.0/lunatic-model-1.0.0.jar
  - mvn install:install-file -Dfile=lunatic-model-1.0.0.jar -DgroupId=fr.insee.lunatic -DartifactId=lunatic-model -Dversion=1.0.0 -Dpackaging=jar

  - wget https://github.com/laurentC35/Eno/releases/download/2.0.0/eno-core-2.0.0.jar
  - mvn install:install-file -Dfile=eno-core-2.0.0.jar -DgroupId=fr.insee.eno -DartifactId=eno-core -Dversion=2.0.0 -Dpackaging=jar

  - mvn install -DskipTests

deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker build -t $DOCKER_USER/eno-ws:$TRAVIS_TAG .

    - docker push $DOCKER_USER/eno-ws:$TRAVIS_TAG
  on:
    tags: true
  
  
