apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eno-ws
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - eno.demo.dev.sspcloud.fr
  rules:
    - host: eno.demo.dev.sspcloud.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: eno-ws
              servicePort: http
