version: '3.1'

services:
  eno:
    build: ./eno
    volumes:
      - "./eno/eno-ws.war:/usr/local/tomcat/webapps/eno-ws.war"
      - "./eno/eno.properties:/usr/local/tomcat/webapps/eno.properties"
    ports:
      - "8282:8080"
